version: 2
jobs:
  build-qa:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Install AWS Client
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip libpython-dev
            sudo pip --version
            sudo pip install awscli --upgrade
            aws --version
      - restore_cache:
          keys:
            - protector-user-client-{{ checksum "yarn.lock" }}
            - protector-user-client-
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Build project
          command: |
            CI=false yarn build:qa
      - setup_remote_docker
      - run:
          name: Docker build process
          command: ./scripts/build-qa.sh
      - run:
          name: Push Docker Image
          command: ./scripts/push-qa.sh
  deploy-qa:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Deploy on QA
          command: |
            ssh ubuntu@dev.passolargo.strider.ag "./protector-v4-infra-dev/scripts/image_pull_credentials/reload_regcred.sh && cd protector-v4-infra-dev/k8s/clients/user-app/ && kubectl delete -f deployment.yaml && kubectl apply -f deployment.yaml"
  build-staging:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Install AWS Client
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip libpython-dev
            sudo pip --version
            sudo pip install awscli --upgrade
            aws --version
      - restore_cache:
          keys:
            - protector-user-client-{{ checksum "yarn.lock" }}
            - protector-user-client-
      - run:
          name: Install yarn dependencies
          command: yarn install
      - run:
          name: Build project
          command: |
            yarn build:staging
      - setup_remote_docker
      - run:
          name: Docker build process
          command: ./scripts/build.sh
      - run:
          name: Push Docker Image
          command: ./scripts/push.sh
workflows:
  version: 2
  build-and-deploy-qa:
    jobs:
      - build-qa:
          context: protector-release-qa
      - deploy-qa:
          context: protector-release-qa
          requires:
            - build-qa
          filters:
            branches:
              only:
                - qa
  build-staging:
    jobs:
      - build-staging:
          context: protector-release-master
          filters:
            branches:
              only:
                - master
